import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

public class MyFirstJDBCProgram {
    public static void main(String[] args) {
        String DB_URL = "jdbc:oracle:thin:@localhost:1521:xe";
        String DB_USER = "system";
        String DB_PASSWORD = "BCA5C";

        Connection con = null;
        Statement stmt = null;

        try {
            // Step 1: Registering the Driver Class
            Class.forName("oracle.jdbc.driver.OracleDriver");

            // Step 2: Open DB Connection
            con = DriverManager.getConnection(DB_URL, DB_USER, DB_PASSWORD);

            // Step 3: Create Statement
            stmt = con.createStatement();

            // Step 4: Drop the table if it exists
            String dropTableSQL = "DROP TABLE student";
            try {
                stmt.executeUpdate(dropTableSQL);
                System.out.println("Existing table 'student' dropped successfully.");
            } catch (SQLException e) {
                // Handle case where the table does not exist
                if (e.getErrorCode() != 942) { // ORA-00942: table or view does not exist
                    throw e;
                }
            }

            // Step 5: Define the SQL query to create a new table
            String createTableSQL = "CREATE TABLE student (" +
                                    "id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                                    "first_name VARCHAR2(50) NOT NULL, " +
                                    "last_name VARCHAR2(50) NOT NULL, " +
                                    "date_of_birth DATE, " +
                                    "email VARCHAR2(100), " +
                                    "enrollment_date DATE DEFAULT SYSDATE" +
                                    ")";

            // Execute the SQL statement to create the table
            stmt.executeUpdate(createTableSQL);
            System.out.println("Table 'student' created successfully.");

            // Step 6: Insert records into the student table
            String insertSQL1 = "INSERT INTO student (first_name, last_name, date_of_birth, email) VALUES ('John', 'Doe', TO_DATE('2000-01-15', 'YYYY-MM-DD'), 'john.doe@example.com')";
            String insertSQL2 = "INSERT INTO student (first_name, last_name, date_of_birth, email) VALUES ('Jane', 'Smith', TO_DATE('1999-05-20', 'YYYY-MM-DD'), 'jane.smith@example.com')";
            String insertSQL3 = "INSERT INTO student (first_name, last_name, date_of_birth, email) VALUES ('Mike', 'Johnson', TO_DATE('2001-09-10', 'YYYY-MM-DD'), 'mike.johnson@example.com')";
            String insertSQL4 = "INSERT INTO student (first_name, last_name, date_of_birth, email) VALUES ('Emily', 'Davis', TO_DATE('1998-12-25', 'YYYY-MM-DD'), 'emily.davis@example.com')";

            // Execute insert statements
            stmt.executeUpdate(insertSQL1);
            stmt.executeUpdate(insertSQL2);
            stmt.executeUpdate(insertSQL3);
            stmt.executeUpdate(insertSQL4);
            System.out.println("Records inserted successfully.");

        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
            // Close resources
            try {
                if (stmt != null) stmt.close();
                if (con != null) con.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }
}
